# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
### Part II - VacationPy

# Now let's use your skills in working with weather data to plan future vacations. Use jupyter-gmaps and the Google Places API for this part of the assignment.

# * **Note:** if you having trouble displaying the maps try running `jupyter nbextension enable --py gmaps` in your environment and retry.

# * Create a heat map that displays the humidity for every city from the part I of the homework.

#   ![heatmap](Images/heatmap.png)

# * Narrow down the DataFrame to find your ideal weather condition. For example:

#   * A max temperature lower than 80 degrees but higher than 70.

#   * Wind speed less than 10 mph.

#   * Zero cloudiness.

#   * Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.

#   * **Note:** Feel free to adjust to your specifications but be sure to limit the number of rows returned by your API requests to a reasonable number.

# * Using Google Places API to find the first hotel for each city located within 5000 meters of your coordinates.

# * Plot the hotels on top of the humidity heatmap with each pin containing the **Hotel Name**, **City**, and **Country**.

#   ![hotel map](Images/hotel_map.png)

# As final considerations:

# * Create a new GitHub repository for this project called `API-Challenge` (note the kebab-case). **Do not add to an existing repo**
# * You must complete your analysis using a Jupyter notebook.
# * You must use the Matplotlib or Pandas plotting libraries.
# * For Part I, you must include a written description of three observable trends based on the data.
# * You must use proper labeling of your plots, including aspects like: Plot Titles (with date of analysis) and Axes Labels.
# * For max intensity in the heat map, try setting it to the highest humidity found in the data set.

# ## Hints and Considerations

# * The city data you generate is based on random coordinates as well as different query times; as such, your outputs will not be an exact match to the provided starter notebook.

# * You may want to start this assignment by refreshing yourself on the [geographic coordinate system](http://desktop.arcgis.com/en/arcmap/10.3/guide-books/map-projections/about-geographic-coordinate-systems.htm).

# * Next, spend the requisite time necessary to study the OpenWeatherMap API. Based on your initial study, you should be able to answer  basic questions about the API: Where do you request the API key? Which Weather API in particular will you need? What URL endpoints does it expect? What JSON structure does it respond with? Before you write a line of code, you should be aiming to have a crystal clear understanding of your intended outcome.

# * A starter code for Citipy has been provided. However, if you're craving an extra challenge, push yourself to learn how it works: [citipy Python library](https://pypi.python.org/pypi/citipy). Before you try to incorporate the library into your analysis, start by creating simple test cases outside your main script to confirm that you are using it correctly. Too often, when introduced to a new library, students get bogged down by the most minor of errors -- spending hours investigating their entire code -- when, in fact, a simple and focused test would have shown their basic utilization of the library was wrong from the start. Don't let this be you!

# * Part of our expectation in this challenge is that you will use critical thinking skills to understand how and why we're recommending the tools we are. What is Citipy for? Why would you use it in conjunction with the OpenWeatherMap API? How would you do so?

# * In building your script, pay attention to the cities you are using in your query pool. Are you getting coverage of the full gamut of latitudes and longitudes? Or are you simply choosing 500 cities concentrated in one region of the world? Even if you were a geographic genius, simply rattling 500 cities based on your human selection would create a biased dataset. Be thinking of how you should counter this. (Hint: Consider the full range of latitudes).

# * Once you have computed the linear regression for one chart, the process will be similar for all others. As a bonus, try to create a function that will create these charts based on different parameters.

# * Remember that each coordinate will trigger a separate call to the Google API. If you're creating your own criteria to plan your vacation, try to reduce the results in your DataFrame to 10 or fewer cities.

# * Lastly, remember -- this is a challenging activity. Push yourself! If you complete this task, then you can safely say that you've gained a strong mastery of the core foundations of data analytics and it will only go better from here. Good luck!

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
output_data_part_one = "output_data/weather_df.csv"

# read it in
city_weather_df = pd.read_csv(output_data_part_one)

# show df
city_weather_df.head()

,City,Lat,Lng,Cloudiness,Wind Speed,Humidity,Max Temp,Date
0,rikitea,-23.12,-134.97,27,13.82,77,75.67,1587665543
1,anadyr,64.75,177.48,0,6.71,84,1.40,1587665543
2,aklavik,68.22,-135.01,90,14.99,71,6.80,1587665543
3,bluff,-46.60,168.33,80,3.00,86,50.00,1587665543
4,kapaa,22.08,-159.32,75,13.87,83,75.20,1587665544

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
# configure gmaps
gmaps.configure(api_key=g_key)

# use the Lat and Lng as locations and Humidity as the weight
locations = city_weather_df[["Lat","Lng"]]
humidity = city_weather_df["Humidity"].astype(float)
fig = gmaps.figure()

In [5]:
# Create a Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
cities_per_conditions = pd.DataFrame(city_weather_df, columns = ["City","Max Temp", "Wind Speed", "Cloudiness"])

max_temp = (cities_per_conditions["Max Temp"]<= 75) & (cities_per_conditions["Max Temp"]>71)
wind_speed = cities_per_conditions["Wind Speed"] <= 7
cloudiness = cities_per_conditions["Cloudiness"]== 0

cities_per_conditions[max_temp & wind_speed & cloudiness]

         City  Max Temp  Wind Speed  Cloudiness
263    castro     73.58        3.56           0
309   haripur     73.99        5.82           0
410  nokaneng     71.04        6.49           0

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
hotels_df = pd.DataFrame(cities_per_conditions, columns=["City", "Country", "Lat", "Lng"])

hotels_df["Hotel Name"]=""

hotels_df

           City  Country  Lat  Lng Hotel Name
0       rikitea      NaN  NaN  NaN
1        anadyr      NaN  NaN  NaN
2       aklavik      NaN  NaN  NaN
3         bluff      NaN  NaN  NaN
4         kapaa      NaN  NaN  NaN
..          ...      ...  ...  ...        ...
534    atherton      NaN  NaN  NaN
535     veraval      NaN  NaN  NaN
536   taoudenni      NaN  NaN  NaN
537  hofgeismar      NaN  NaN  NaN
538  mandalgovi      NaN  NaN  NaN

[539 rows x 5 columns]

In [8]:
target_coords = f"{hotel_df["Lat"][0]},{hotel_df["Lng"][O]}
target_search = "hotel"
target_radius = 5000
target_type = "hotel"

# params
params = {"location": target_coords,
          "keyword": target_search,
          "radius": target_radius,
          "type": target_type,
          "key": g_key
}

google_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# run api
api_response = requests.get(base_url, params=params)

SyntaxError: invalid syntax (<ipython-input-8-6d4ddaea90a0>, line 1)

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotels_local.iterrows()]
city_weather_df = hotels_local[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure